### PR TITLE
Add `export!` macros

### LINKED ISSUE #76: Add macros for generating wasi world export bindings
Implementing WASI exports correctly is verbose and requires a somewhat-deep understanding of wit-bindgen features, especially if you want to reuse the types from this crate:

```rust
wit_bindgen::generate!({
    path: "<copy-of-wasi-wit>", // Must match wit in this crate!
    world: "wasi:http/proxy",
    exports: {
        "wasi:http/incoming-handler": MyIncomingHandler,
    },
    with: {
        "wasi:io/poll": wasi::io::poll,
        // ...
    },
});

impl exports::wasi::http::incoming_handler::Guest for MyIncomingHandler { ... }
```

We can make this easier - at least for many common cases - by providing simple macros that wrap `wit_bindgen::generate!`, e.g. as an equivalent to the above:

```rust
wasi::http::export_incoming_handler!(MyIncomingHandler);

// exports::incoming_handler aliasing exports::wasi::http::incoming_handler
impl exports::incoming_handler::Guest for MyIncomingHandler { ... }
```

If we need to support extra options on these macros the wit-bindgen style could be allowed as an alternative, e.g.:

```rust
wasi::http::export_incoming_handler!({
    export: MyIncomingHandler,
    wasi_path: path::to::wasi::crate,
});
```

### PR DESCRIPTION
**Pull request by lann**
Also update bindings.rs with wit-bindgen 0.19.2.

Closes #76 

```rust
use wasi::http::types::{IncomingRequest, ResponseOutparam};

wasi::http::incoming_handler::export!(Handler);

struct Handler;

impl exports::wasi::http::incoming_handler::Guest for Handler {
    fn handle(request: IncomingRequest, response_out: ResponseOutparam) {
        ...
    }
}
```

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
This all looks great to me, thanks for both the suggestion and the implementation!

**Comment by alexcrichton** [comment]
Oh I realize now though that this isn't tested on CI. Can you add a CI check to ensure that the crate builds with this feature enabled?

For other nice-to-haves, feel free to defer these to either a future PR or a future contributor:

* These would probably make good entries in documentation at the crate level along with instructions of how to build.
* The `wasi:cli/run` macro may want some caution about it to indicate that it doesn't work with `fn main() {}` and `fn main() {}` otherwise works with the "command" adapter
* It'd be good to have a CLI check to ensure that these build the expected world, perhaps using `wasm-tools component targets`

Again though these points aren't critical, only the CI bit I think is critical to have before landing.

**Comment by lann** [comment]
> Can you add a CI check to ensure that the crate builds with this feature enabled?
> It'd be good to have a CLI check to ensure that these build the expected world, perhaps using `wasm-tools component targets`

Added `wasmtime run` for the cli/command example and `wasm-tools component targets` for the http/proxy example.

> These would probably make good entries in documentation at the crate level along with instructions of how to build.

Added "Export Macros" section to root docs.

> The `wasi:cli/run` macro may want some caution about it to indicate that it doesn't work with `fn main() {}` and `fn main() {}` otherwise works with the "command" adapter

Added section to macro docs.

**Comment by alexcrichton** [comment]
Thanks again for all this!

**Pull request merged**
