### PR TITLE
Update wit-bindgen and bump to 0.13.0

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates wit-bindgen to 0.21.0 which brings in some minor updates to generated code in addition to a new `wit-bindgen-rt` crate dependency to use as well. This avoids the need to depend on the `wit-bindgen` crate at all through some updated options to the CLI bindings generator.

Additionally this bumps the crate to 0.13.0 to release these updated change in addition to the refactoring for the export-related macros previously.

### CODE REVIEW

**Comment by sunfishcode** [comment]
> This commit updates wit-bindgen to 0.21.0 which brings in some minor updates to generated code in addition to a new `wit-bindgen-rt` crate dependency to use as well. This avoids the need to depend on the `wit-bindgen` crate at all through some updated options to the CLI bindings generator.

What is the advantage of not depending on `wit-bindgen`? We depend on `bitflags` either way, and `wit-bindgen` itself appears to have very little in it other than re-exports of `wit-bindgen-rt`. Is it the code in the `pre_wit_bindgen_0_20_0` module?

**Comment by alexcrichton** [comment]
Oh no real advantage per-se, but I figure it's at least a bit nicer in terms of "fewer deps" and better aligns with what cargo component is doing. AFAIK there's no technical benefit for doing so.

**Comment by sunfishcode** [comment]
Why is wit-bindgen-rt a separate crate? Would it make sense to just fold it into wit-bindgen?

**Comment by alexcrichton** [comment]
That was motivated by https://github.com/bytecodealliance/cargo-component/issues/241 where I believe the issue was that `cargo add` was conflicting with the default dependency injected by `cargo component` and it was easier to manage if `cargo component` didn't have to deal with the features of a `wit-bindgen` dependency at all.

**Review by sunfishcode — APPROVED** [review]

**Pull request merged**
