### PR TITLE
Add a wasi-ephemeral crate to build with ephemeral WASI interfaces

### PR DESCRIPTION
**Pull request by joshtriplett**
Developers working on WASI interfaces can use the wasi-ephemeral crate
as a path dependency or git dependency, to build and run with the
ephemeral WASI interface rather than the latest snapshot.
(wasi-ephemeral uses publish=false and will not be uploaded to
crates.io.)

wasi-ephemeral builds with a build.rs script, so that it automatically
rebuilds on changes to the witx file.

wasi-ephemeral also supports building with an arbitrary witx file, using
the WASI_EPHEMERAL_WITX environment variable.

Note that wasi-ephemeral won't build with the current
wasi_ephemeral_preview.witx until generate-raw can render handles (and
no longer panics with "don't know how to render a handle"). However, I
can confirm that it works with WASI_EPHEMERAL_WITX pointed to either
wasi_snapshot_preview1 (in which case wasi-ephemeral becomes a copy
of wasi) or the old wasi_unstable.

### CODE REVIEW

**Comment by joshtriplett** [comment]
The first two commits are https://github.com/bytecodealliance/wasi/pull/29 and https://github.com/bytecodealliance/wasi/pull/30, which can be merged independently of this.

**Comment by alexcrichton** [comment]
Want to also add a README to the new crate directory explaining how to use it?

**Comment by joshtriplett** [comment]
@alexcrichton Done! As soon as #33 goes in, this can go in.

**Comment by alexcrichton** [comment]
Oh as one final comment, can this be built on CI? Otherwise r=me

**Comment by joshtriplett** [comment]
@alexcrichton I'd love to do that; are we prepared to commit to supporting builds of any new version of the WASI submodule and their versions of wasi-ephemeral (that we update the submodule to)? That would mean we *have* to make changes like #33 before we can pull in new versions of the WASI submodule. I'm entirely in favor of that, I just want to confirm that others are as well before adding that to CI.

**Comment by alexcrichton** [comment]
That's a good point, but I would prefer that we test building the crate while we have the crate, and then if a WASI submodule update was too difficult because it breaks the ephemeral crate, we could just comment out that CI config until it's fixed.

**Comment by alexcrichton** [comment]
👍

**Comment by joshtriplett** [comment]
Thanks!

**Pull request merged**
