### PR TITLE
Update to wit-bindgen 0.20.0

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates the bindings generator to 0.20.0 and refactors the existing support for exporting macros to use the new features of 0.20.0 as well. The `macros` crate feature is now no longer required (yay!) and all the traits to implement are already present in the crate now.

### CODE REVIEW

**Comment by lann** [comment]
Nice!

My only comment is about naming; from an external perspective its a little odd that the macro names don't include the package name. If it was e.g. `http_proxy_export` it would line up nicely between `wasi:http/proxy` and `wasi::http_proxy_export`.

I don't think its critically important for the `wasi` package itself but this crate probably does set a bit of a precedent for other similar crates.

**Comment by alexcrichton** [comment]
Good point! I've reverted back to the names you added prior, with one change to rename the `incoming_handler` module to `proxy` instead to reflect a bit how the world is `wasi:http/proxy`. Makes me think I should probably update wit-bindgen to perhaps do this by default.

**Comment by lann** [comment]
Makes sense to me. Should the `run` mod be renamed to `command` too?

**Comment by alexcrichton** [comment]
Oop yes, good point

**Review by sunfishcode — APPROVED** [review]

**Pull request merged**
